models/Monitoringchok.php
<?php

namespace app\models;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\db\ActiveRecord;
use yii\behaviors\BlameableBehavior;
use yii\web\UploadedFile;
use yii\helpers\Html;
use Yii;

/**
 * This is the model class for table "{{%monitoringchok}}".
 *
 * @property integer $kromikNong
 * @property string $noticeReceivedDate
 * @property integer $upazilaNam
 * @property string $mamlaNong
 * @property string $mamlarBochor
 * @property integer $biggAdaloterNam
 * @property string $emailSendingDate
 * @property string $sfReceiptDate
 * @property string $sfReceiptOriginalDate
 * @property string $sfSendToJusticeDate
 * @property string $montobo
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property Upazila $upazilaNam0
 * @property BiggAdalot $biggAdaloterNam0
 */
class Monitoringchok extends \yii\db\ActiveRecord
{
    
    public $file;
    const STATUS_FINISHED   = 10;
    const STATUS_INPROGRESS = 1;
    const STATUS_PENDING  = 0;
	
	public $statusList = [
        self::STATUS_FINISHED   => 'Finished',
        self::STATUS_INPROGRESS => 'In-Progress',
        self::STATUS_PENDING  => 'Pending'
    ];
	
	
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%monitoringchok}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['noticeReceivedDate', 'upazilaNam', 'mamlaNong', 'mamlarBochor'], 'required'],
            [['noticeReceivedDate', 'mamlarBochor', 'emailSendingDate', 'biggAdaloterNam', 'sfReceiptDate', 'sfReceiptOriginalDate', 'status', 'sfSendToJusticeDate', 'created_at', 'updated_at'], 'safe'],
            [['upazilaNam', 'biggAdaloterNam', 'status'], 'integer'],
            [['mamlaNong'], 'string', 'max' => 6],
            [['file'],'file'],
            [['scanfile'],'string'],
            [['montobo'], 'string', 'max' => 256],
            [['upazilaNam'], 'exist', 'skipOnError' => true, 'targetClass' => Upazila::className(), 'targetAttribute' => ['upazilaNam' => 'upazila_nong']],
            [['biggAdaloterNam'], 'exist', 'skipOnError' => true, 'targetClass' => BiggAdalot::className(), 'targetAttribute' => ['biggAdaloterNam' => 'biggAdalot_id']],
        ];
    }
	
	public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => new Expression('NOW()'),
            ],
            'blameable' => [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
                ],
             
        ];
    }
    
    public function getScanfileurl()
    {				
		//return \Yii::$app->request->baseUrl.'/'.$this->scanfile;
      if(!empty($this->scanfile)) {
	return Html::img(Yii::$app->request->baseUrl.'/'.$this->scanfile,['alt'=>'', 'class' => 'img-rounded', 'width'=>'100px','height'=>'100px','title'=>'www.ltb.com.bd']);	 
      } else {
        return Html::img(Yii::$app->request->baseUrl.'/'.'uploads/'.'scanfile.png',['alt'=>'', 'class' => 'img-rounded', 'width'=>'100px','height'=>'100px','title'=>'www.ltb.com.bd']);	 
      }      
    }
    
    public function getImageFile() 
    {
		if(isset($this->scanfile)){
			return $this->scanfile;
		}        
    }
	
	 public function uploadImage() {
        $image = UploadedFile::getInstance($this, 'scanfile');			              
        
		if (empty($image)) {
            return false;
        }		
		$this->file = $image->name;
        $ext = end((explode(".", $image->name)));        
        $this->scanfile = Yii::$app->security->generateRandomString().".{$ext}";
        
        return $image;        
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'kromikNong' => Yii::t('app', 'Kromik Nong'),
            'noticeReceivedDate' => Yii::t('app', 'Notice Received Date'),
            'upazilaNam' => Yii::t('app', 'Upazila Nam'),
            'mamlaNong' => Yii::t('app', 'Mamla Nong'),
            'mamlarBochor' => Yii::t('app', 'Mamlar Bochor'),
            'biggAdaloterNam' => Yii::t('app', 'Bigg Adaloter Nam'),
            'emailSendingDate' => Yii::t('app', 'Email Sending Date'),
            'sfReceiptDate' => Yii::t('app', 'Sf Receipt Date'),
            'sfReceiptOriginalDate' => Yii::t('app', 'Sf Receipt Original Date'),
            'sfSendToJusticeDate' => Yii::t('app', 'Sf Send To Justice Date'),
            'montobo' => Yii::t('app', 'Montobo'),
            'status' => Yii::t('app', 'Status'),
            'scanfile' => Yii::t('app', 'Scan File'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_by' => Yii::t('app', 'Updated By'),
        ];
    }
	
	public function getStatusName($status)
    {
        return $this->statusList[$status];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpazilaNam0()
    {
        return $this->hasOne(Upazila::className(), ['upazila_nong' => 'upazilaNam']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBiggAdaloterNam0()
    {
        return $this->hasOne(BiggAdalot::className(), ['biggAdalot_id' => 'biggAdaloterNam']);
    }
}

controllers/MonitoringchokController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Monitoringchok;
use app\models\Notification;
use app\models\MonitoringchokSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * MonitoringchokController implements the CRUD actions for Monitoringchok model.
 */
class MonitoringchokController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];		
    }

    /**
     * Lists all Monitoringchok models.
     * @return mixed
     */
    public function actionIndex()
    {
		$this->layout = 'dashboard';
        $searchModel = new MonitoringchokSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Monitoringchok model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
		$this->layout = 'dashboard';
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Monitoringchok model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
		$this->layout = 'dashboard';
        $model = new Monitoringchok();
        $recipient_id = 41;
		$userOf = \Yii::$app->user->identity->userof;
        if ($model->load(Yii::$app->request->post())) {
	        if($model->file = UploadedFile::getInstance($model, 'scanfile'))
	        {
	            $mamlaNong = $model->mamlaNong;
				$model->file->saveAs('uploads/'.$mamlaNong.'.'.$model->file->extension);			
				$model->scanfile = 'uploads/'.$mamlaNong.'.'.$model->file->extension;
		    }
		    
		    if($userOf == 17 || $userOf == 18 || $userOf == 19 || $userOf == 20 || $userOf == 21 || $userOf == 22 || $userOf == 23 || $userOf == 24 || $userOf == 25 || $userOf == 26 || $userOf == 27 || $userOf == 28 || $userOf == 29 || $userOf == 30 || $userOf == 31 || $userOf == 32 || $userOf == 33 || $userOf == 34 || $userOf == 35 || $userOf == 36 || $userOf == 37 || $userOf == 38 || $userOf == 39 || $userOf == 40 ) {
				$model->biggAdaloterNam = \Yii::$app->user->identity->userof;
			}     					
			if($model->save()) {				
				Notification::notify(Notification::KEY_NEW_CASE, $recipient_id, $model->kromikNong);	
			}
            //return $this->redirect(['view', 'id' => $model->kromikNong]);
            return $this->redirect('index');
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Monitoringchok model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
		$this->layout = 'dashboard';
        $model = $this->findModel($id);
		$oldfile = $model->getImageFile();		
        if ($model->load(Yii::$app->request->post())) {
        	$image = $model->uploadImage();
			if ($image !== false) { 
				$path = $model->getImageFile();
				$image->saveAs($path);
			} else {			
				$model->scanfile = $oldfile;
			}	        	
				$recipient_id = $model->upazilaNam;
				if (($model->emailSendingDate) == '0000-00-00' || ($model->emailSendingDate) == '' || $model->emailSendingDate <= $model->emailSendingDate) {
					Notification::notify(Notification::KEY_CASE_REMINDER_EMAIL, $recipient_id, $model->mamlaNong);
				}
				if(($model->sfReceiptDate) == '0000-00-00' || ($model->sfReceiptDate) == '' || $model->sfReceiptDate <= $model->sfReceiptDate) {
					Notification::notify(Notification::KEY_CASE_REMINDER_SF_RECEIPT_DATE, $recipient_id, $model->mamlaNong);
				}
				$recipient_id = 41;
				if(($model->sfReceiptOriginalDate) == '0000-00-00' || ($model->sfReceiptOriginalDate) == '' || $model->sfReceiptOriginalDate <= $model->sfReceiptOriginalDate) {
					Notification::notify(Notification::KEY_CASE_REMINDER_SF_ORIGINAL_RECEIPT_DATE, $recipient_id, $model->mamlaNong);
				}
				$recipient_id = $model->biggAdaloterNam;
				if(($model->sfSendToJusticeDate) == '0000-00-00' || ($model->sfSendToJusticeDate) == '' || $model->sfSendToJusticeDate <= $model->sfSendToJusticeDate) {
					Notification::notify(Notification::KEY_CASE_REMINDER_SF_DATE_FOR_COURT, $recipient_id, $model->mamlaNong);
				}
	            
            $model->save();
            return $this->redirect('index');
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Monitoringchok model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
		$this->layout = 'dashboard';
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Monitoringchok model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Monitoringchok the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Monitoringchok::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/monitoringchok/_form-stable.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Upazila;
use app\models\BiggAdalot;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Monitoringchok */
/* @var $form yii\widgets\ActiveForm */
$userOf = \Yii::$app->user->identity->userof;
?>
<?php if (Yii::$app->user->can('admin')){ ?>
<div class="monitoringchok-form">

   <?php $form = ActiveForm::begin(['id' => 'form-user','options' => ['enctype' => 'multipart/form-data']]); ?>    
    
	<?= $form->field($model, 'upazilaNam')->dropDownList(
		ArrayHelper::map(Upazila::find()->all(), 'upazila_nong', 'upazila_nam'),
		['prompt' => 'উপজেলা নির্বাচন করুন']
	) ?>
	
	<div class="row">
		<?= Html::activeLabel($model, 'mamlaNong', [
			'label'=> 'মামলা নং', 
			'class'=>'col-lg-1 control-label'
		]) ?>
		<div class="col-lg-2">			
			<?php echo $form->field($model, 'mamlaNong', [
					   'inputOptions' => ['autofocus' => false, 'class' => 'form-control transparent']
				 ])->textInput()->input('mamlaNong', ['placeholder' => 'মামলা নাম্বার'])->label(false); ?>
		</div>
		<div class="col-lg-2">			
			<?php echo $form->field($model, 'mamlarBochor', [
					   'inputOptions' => ['autofocus' => false, 'class' => 'form-control transparent']
				 ])->textInput()->input('mamlarBochor', ['placeholder' => 'মামলার বছর'])->label(false); ?>
		</div>
		<div class="col-lg-8"></div>
    </div>    
	<?php /*echo $form->field($model, 'biggAdaloterNam', [
			   'inputOptions' => ['autofocus' => false, 'class' => 'form-control transparent']
		 ])->textInput()->input('biggAdaloterNam', ['placeholder' => 'আদালত তিন']) */?>
	<?= $form->field($model, 'biggAdaloterNam')->dropDownList(
		ArrayHelper::map(BiggAdalot::find()->all(), 'biggAdalot_id', 'biggAdaloterNam'),
		['prompt' => 'বিজ্ঞ আদালত নির্বাচন করুন']
	) ?>
	
	<?= $form->field($model, 'noticeReceivedDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) ?> 
		 
	<?= $form->field($model, 'emailSendingDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) ?>    
	
	<?= $form->field($model, 'sfReceiptDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) ?>  
		    
	<?= $form->field($model, 'sfReceiptOriginalDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) ?> 
    
	<?= $form->field($model, 'sfSendToJusticeDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) ?> 
    
	<?php echo $form->field($model, 'montobo', [
			   'inputOptions' => ['autofocus' => false, 'class' => 'form-control transparent']
		 ])->textInput()->input('montobo', ['placeholder' => 'কথা']); ?>
    
	<?= $form->field($model, 'status')->dropDownList($model->statusList, ['prompt' => 'কাজের অগ্রগতি'])->label(false) ?>
	
	<?= $form->field($model, 'scanfile')->fileInput(); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Cancel'), ['monitoringchok/index'], ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php } elseif($userOf === 17 || $userOf === 18 || $userOf === 19 || $userOf === 20 || $userOf === 21 || $userOf === 22 || $userOf === 23 || $userOf === 24 || $userOf === 25 || $userOf === 26 || $userOf === 27 || $userOf === 28 || $userOf === 29 || $userOf === 30 || $userOf === 31 || $userOf === 32 || $userOf === 33 || $userOf === 34 || $userOf === 35 || $userOf === 36 || $userOf === 37 || $userOf === 38 || $userOf === 39 || $userOf === 40 ) { ?>
	<div class="monitoringchok-form">

   <?php $form = ActiveForm::begin(['id' => 'form-user','options' => ['enctype' => 'multipart/form-data']]); ?>    
    
	<?= $form->field($model, 'upazilaNam')->dropDownList(
		ArrayHelper::map(Upazila::find()->all(), 'upazila_nong', 'upazila_nam'),
		['prompt' => 'উপজেলা নির্বাচন করুন']
	) ?>
	
	<div class="row">
		<?= Html::activeLabel($model, 'mamlaNong', [
			'label'=> 'মামলা নং', 
			'class'=>'col-lg-1 control-label'
		]) ?>
		<div class="col-lg-2">			
			<?php echo $form->field($model, 'mamlaNong', [
					   'inputOptions' => ['autofocus' => false, 'class' => 'form-control transparent']
				 ])->textInput()->input('mamlaNong', ['placeholder' => 'মামলা নাম্বার'])->label(false); ?>
		</div>
		<div class="col-lg-2">			
			<?php echo $form->field($model, 'mamlarBochor', [
					   'inputOptions' => ['autofocus' => false, 'class' => 'form-control transparent']
				 ])->textInput()->input('mamlarBochor', ['placeholder' => 'মামলার বছর'])->label(false); ?>
		</div>
		<div class="col-lg-8"></div>
        </div>
        
        <?= $form->field($model, 'noticeReceivedDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) ?>   	
		 
	<?php /*= $form->field($model, 'emailSendingDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) */?>    
	
	<?php /*= $form->field($model, 'sfReceiptDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) */?>  
		    
	<?php /*= $form->field($model, 'sfReceiptOriginalDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) */?> 
    
	<?php /*= $form->field($model, 'sfSendToJusticeDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) */ ?> 
    
	<?php echo $form->field($model, 'montobo', [
			   'inputOptions' => ['autofocus' => false, 'class' => 'form-control transparent']
		 ])->textInput()->input('montobo', ['placeholder' => 'কথা']); ?>
    
	<?= $form->field($model, 'status')->dropDownList($model->statusList, ['prompt' => 'কাজের অগ্রগতি'])->label(false) ?>
	
	<?= $form->field($model, 'scanfile')->fileInput(); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Cancel'), ['monitoringchok/index'], ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php } else { ?>
	<div class="monitoringchok-form">
	
    <?php $form = ActiveForm::begin(['id' => 'form-user','options' => ['enctype' => 'multipart/form-data']]); ?>

    <?php /*= $form->field($model, 'noticeReceivedDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) */?> 
    
	<?php /*= $form->field($model, 'upazilaNam')->dropDownList(
		ArrayHelper::map(Upazila::find()->all(), 'upazila_nong', 'upazila_nam'),
		['prompt' => 'উপজেলা নির্বাচন করুন']
	) */?>
	
	 <div class="row">
		<?php /*=// Html::activeLabel($model, 'mamlaNong', [
			//'label'=> 'মামলা নং', 
			//'class'=>'col-lg-1 control-label'
		//]) */ ?>
		<div class="col-lg-2">			
			<?php// echo $form->field($model, 'mamlaNong', [
				//	   'inputOptions' => ['autofocus' => false, 'class' => 'form-control transparent']
				// ])->textInput()->input('mamlaNong', ['placeholder' => 'মামলা নাম্বার'])->label(false); ?>
		</div>
		<div class="col-lg-2">			
			<?php //echo $form->field($model, 'mamlarBochor', [
					 //  'inputOptions' => ['autofocus' => false, 'class' => 'form-control transparent']
				// ])->textInput()->input('mamlarBochor', ['placeholder' => 'মামলার বছর'])->label(false); ?>
		</div>
		<div class="col-lg-8"></div>
    </div>   
	<?php /*echo $form->field($model, 'biggAdaloterNam', [
			   'inputOptions' => ['autofocus' => false, 'class' => 'form-control transparent']
		 ])->textInput()->input('biggAdaloterNam', ['placeholder' => 'আদালত তিন']) */?>
	<?php /* $form->field($model, 'biggAdaloterNam')->dropDownList(
		ArrayHelper::map(BiggAdalot::find()->all(), 'biggAdalot_id', 'biggAdaloterNam'),
		['prompt' => 'বিজ্ঞ আদালত নির্বাচন করুন']
	) */?>
		 
	<?php /*= $form->field($model, 'emailSendingDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) */ ?>    
	
	<?php /* = $form->field($model, 'sfReceiptDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) */?>  
		    
	<?= $form->field($model, 'sfReceiptOriginalDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) ?> 
    
	<?php /*= $form->field($model, 'sfSendToJusticeDate')->widget(DatePicker::className(), [			
		'value' => date('Y-m-d'),
		'type' => DatePicker::TYPE_COMPONENT_APPEND,
		'removeButton' => [
			'icon'=>'trash',
		],
		'pickerButton' => [
			'icon'=>'ok',
		],
		'pluginOptions' => [
			'autoclose'=>true,
			'format' => 'yyyy-mm-dd'
		]
	]) */?> 
    
	<?php echo $form->field($model, 'montobo', [
			   'inputOptions' => ['autofocus' => false, 'class' => 'form-control transparent']
		 ])->textInput()->input('montobo', ['placeholder' => 'কথা']); ?>    	
	
	<?php /*= $form->field($model, 'scanfile')->fileInput(); */ ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>	

</div>
<?php } ?>

views/monitoringchok/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Monitoringchok */

$this->title = Yii::t('app', 'Create Monitoringchok');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Monitoringchoks'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="monitoringchok-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>