models/User.php
<?php
namespace app\models;

use app\rbac\models\Role;
use kartik\password\StrengthValidator;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\db\ActiveRecord;
use yii\behaviors\BlameableBehavior;
use yii\helpers\Html;
use Yii;


class User extends UserIdentity
{
    
    public $file;
    const STATUS_ACTIVE   = 10;
    const STATUS_INACTIVE = 1;    

    
    public $statusList = [
        self::STATUS_ACTIVE   => 'Active',
        self::STATUS_INACTIVE => 'Inactive',        
    ];

   
    public $password;

  
    public $item_name;

  
    public function rules()
    {
        return [
            [['username','first_name','last_name','designation','address'], 'filter', 'filter' => 'trim'],
            ['username', 'required','message'=> 'ব্যবহারকারীর নাম ফাঁকা রাখা যাবে না.'],
            [['username'], 'match', 'pattern' => '/^[a-zA-Z]+$/','message'=>Yii::t('app','শুধুমাত্র বর্ণানুক্রমিক অক্ষর শব্দ টাইপ করুন।') ],
            [['first_name','last_name','designation'], 'match', 'pattern' => '/^[a-zA-Z. ]+$/','message'=>Yii::t('app','শুধুমাত্র বর্ণানুক্রমিক অক্ষর ও . শব্দ টাইপ করুন।') ],
			[['first_name','last_name','designation','address', 'mobile_no'], 'required','message'=> 'এই ক্ষেত্র পূরণ করতে হবে'],
            ['username', 'unique', 'targetClass' => '\app\models\User', 'message' => 'এই ব্যবহারকারীর নাম ইতিমধ্যেই নেওয়া হয়েছে ।'],
            [['username','first_name','last_name','designation'], 'string', 'min' => 2, 'max' => 64, 'message' => 'কমপক্ষে 2 টি অক্ষর থাকা উচিত'],
			['address', 'string', 'min' => 2, 'max' => 255, 'message' => 'কমপক্ষে 2 টি অক্ষর থাকা উচিত'],
			[['mobile_no'], 'match', 'pattern' => '/^[0-9]+$/','message'=>Yii::t('app','শুধুমাত্র সংখ্যাসূচক অক্ষর টাইপ করুন ।') ],  	   
			['mobile_no', 'integer', 'min' => 11, 'message'=>'মোবাইল নম্বর অন্তত 11 টি অক্ষর থাকা উচিত'],  	   	    
            ['username', 'string', 'min' => 2, 'max' => 255],
            ['username', 'match',  'not' => true,
                
                'pattern' => '/\b('.Yii::$app->params['user.spamNames'].')\b/i',
                'message' => Yii::t('app', 'It\'s impossible to have that username.')],          
            ['username', 'unique', 
                'message' => Yii::t('app', 'This username has already been taken.')],

            ['email', 'filter', 'filter' => 'trim'],
            ['email', 'required','message'=> 'ই-মেইল নাম ফাঁকা রাখা যাবে না.'],
            ['email', 'email'],
            ['email', 'string', 'max' => 32],
            ['email', 'unique', 
                'message' => Yii::t('app', 'This email address has already been taken.')],

            ['password', 'string', 'min' => 6,'max'=>32],
            ['password', 'required', 'on' => 'create'],
            [['userof'], 'integer'],
            $this->passwordStrengthRule(),
            ['item_name', 'required'],
            [['file'],'file'],
	    [['photo'], 'string'],	
            ['status', 'required'],
            ['item_name', 'string', 'min' => 3, 'max' => 64]
        ];
    }
    
    

    private function passwordStrengthRule()
    {
        
        $fsp = Yii::$app->params['fsp'];

        
        $strong = [['password'], StrengthValidator::className(), 'preset'=>'normal'];

        
        $normal = ['password', 'string', 'min' => 6];

        
        return ($fsp) ? $strong : $normal;
    }


    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => new Expression('NOW()'),
            ],
            'blameable' => [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
                ],
             
        ];
    }

 
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'username' => Yii::t('app', 'Username'),
			'first_name' => Yii::t('app', 'First Name'),
			'last_name' => Yii::t('app', 'Last Name'),
			'designation' => Yii::t('app', 'Designation'),
			'address' => Yii::t('app', 'Address'),
			'mobile_no' => Yii::t('app', 'Mobile No'),
			'userof' => Yii::t('app', 'Userof'),
            'password' => Yii::t('app', 'Password'),
            'email' => Yii::t('app', 'Email'),
            'status' => Yii::t('app', 'Status'),
            'photo' => Yii::t('app', 'Photo'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'item_name' => Yii::t('app', 'Role'),
        ];
    }

  
    public function getRole()
    {
        
        return $this->hasOne(Role::className(), ['user_id' => 'id']);
    }


    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }  
    
  
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email]);
    } 

    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => User::STATUS_ACTIVE,
        ]);
    }


    public static function findByAccountActivationToken($token)
    {
        return static::findOne([
            'account_activation_token' => $token,
            'status' => User::STATUS_INACTIVE,
        ]);
    }
  

    public function getStatusName($status)
    {
        return $this->statusList[$status];
    }

 
    public function getRoleName()
    {
        
        if ($this->role) {
            return $this->role->item_name;
        }
        
        
        return '@uthenticated';
    }

    
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }
    
    
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

  
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

 
    public function generateAccountActivationToken()
    {
        $this->account_activation_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

 
    public function removeAccountActivationToken()
    {
        $this->account_activation_token = null;
    }
    
    public function getImageurl()
	{		
		if(!empty($this->photo)) {
			return Html::img(Yii::$app->request->baseUrl.'/'.$this->photo,['alt'=>'', 'class' => 'img-circle', 'width'=>'40px','height'=>'40px','title'=>'']);	 
		} else {
return Html::img(Yii::$app->request->baseUrl.'/'.'uploads/'.'profilePhoto.jpg',['alt'=>'', 'class' => 'img-circle', 'width'=>'40px','height'=>'40px','title'=>'']);	 
		}		
	}
    public function getPhotourl()
	   {	
	   	if(!empty($this->photo))
	   	{					
			return Html::img(Yii::$app->request->baseUrl.'/'.$this->photo,['alt'=>'', 'class' => 'img-circle', 'width'=>'40px','height'=>'40px','title'=>'image title']);
		} else {
	return Html::img(Yii::$app->request->baseUrl.'/'.'uploads/'.'profilePhoto.jpg',['alt'=>'', 'class' => 'img-circle', 'width'=>'40px','height'=>'40px','title'=>'image title']);
		}	 
	   }

	public function getImageFile() 
    	{
		if(isset($this->photo)){
			return $this->photo;
		}        
    	}
	
	  /**
     * @return \yii\db\ActiveQuery
     */
    public function getMonitoringchoks()
    {
        return $this->hasMany(Monitoringchok::className(), ['userof' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserof0()
    {
        return $this->hasOne(Userof::className(), ['userof_id' => 'userof']);
    }
}

controllers/UserController.php
<?php
namespace app\controllers;

use app\models\User;
use app\models\UserSearch;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;
use yii\behaviors\TimestampBehavior;
use yii\helpers\Setup;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;
use Yii;


class UserController extends AppController
{
    
    protected $_pageSize = 10;

   
    public function actionIndex()
    {
		$this->layout = 'dashboard';
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $this->_pageSize);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
	
	public function behaviors()
	{
		return [
			'timestamp' => [
				'class' => TimestampBehavior::className(),
				'attributes' => [
					ActiveRecord::EVENT_BEFORE_INSERT => 'created_at',
					ActiveRecord::EVENT_BEFORE_UPDATE => 'update_at',
				],
				'value' => function() { 
					return date('U'); // unix timestamp 
				},
			],
		];
	}
	
   
    public function actionView($id)
    {
		$this->layout = 'dashboard';
        return $this->render('view', ['model' => $this->findModel($id)]);
    }

  
    public function actionCreate()
    {
		$this->layout = 'dashboard';
        $user = new User(['scenario' => 'create']);

        if (!$user->load(Yii::$app->request->post())) {
            return $this->render('create', ['user' => $user]);
        }
        
	if ($user->file = UploadedFile::getInstance($user,'photo')) 
	{
	        $userName = $user->username;
		$user->file->saveAs('uploads/'.$userName.'.'.$user->file->extension);			
		$user->photo = 'uploads/'.$userName.'.'.$user->file->extension;
	}
	
        $user->setPassword($user->password);
        $user->generateAuthKey();
		//$user->created_at = date('Y-m-d h:m:s');		

        if (!$user->save()) {
            return $this->render('create', ['user' => $user]);
        }

        $auth = Yii::$app->authManager;
        $role = $auth->getRole($user->item_name);
        $info = $auth->assign($role, $user->getId());

        if (!$info) {
            Yii::$app->session->setFlash('error', Yii::t('app', 'There was some error while saving user role.'));
        }

        return $this->redirect('index');
    }

   
    public function actionUpdate($id)
    {
		$this->layout = 'dashboard';
       
        $user = $this->findModel($id);

        $auth = Yii::$app->authManager;        
       
        if ($roles = $auth->getRolesByUser($id)) {
          
            $role = array_keys($roles)[0]; 
        }

        
        $oldRole = (isset($role)) ? $auth->getRole($role) : $auth->getRole('officeassistant');

        
        $user->item_name = $oldRole->name;

        if (!$user->load(Yii::$app->request->post())) {
            return $this->render('update', ['user' => $user, 'role' => $user->item_name]);
        }

      
        if ($user->password) {
            $user->setPassword($user->password);
        }

       
        if ($user->status == User::STATUS_ACTIVE && $user->account_activation_token != null) {
            $user->removeAccountActivationToken();
        }         
	if ($user->load(Yii::$app->request->post())) {
		if( $user->save() ) {			
		if ($user->photo !== false) { 
			if ($user->file = UploadedFile::getInstance($user,'photo')) 
			{
				$userName = $user->username;				
				$user->file->saveAs('uploads/'.$userName.'.'.$user->file->extension);			
				$user->photo = 'uploads/'.$userName.'.'.$user->file->extension;
				
			} else {
				$oldfile = $user->getImageFile();
				//$oldfile = 'uploads/profilePhoto.jpg';
				$user->photo = $oldfile;	 	 					 
				// echo '<h1>'.'Add Profile Photo'.'</h1>';
				// return $this->render('update', ['user' => $user, 'role' => $user->item_name]);
			}
		    }
		}
	}
        if (!$user->save()) {
            return $this->render('update', ['user' => $user, 'role' => $user->item_name]);
        }

        
        $newRole = $auth->getRole($user->item_name);
        
        $userId = $user->getId();
        
        
        if ($auth->revoke($oldRole, $userId)) {
            $info = $auth->assign($newRole, $userId);
        }

      
        if (!isset($role)) {
            $info = $auth->assign($newRole, $userId);
        }

        if (!$info) {
            Yii::$app->session->setFlash('error', Yii::t('app', 'There was some error while saving user role.'));
        }

       
		return $this->redirect('index');
    }

   
    public function actionDelete($id)
    {
		$this->layout = 'dashboard';        
        if (!$this->findModel($id)->delete()) {
            throw new ServerErrorHttpException(Yii::t('app', 'We could not delete this user.'));
        }

        $auth = Yii::$app->authManager;
        $info = true; 

       
        if ($roles = $auth->getRolesByUser($id)) {
          
            $role = array_keys($roles)[0]; 
        }

       
        if (isset($role)) {
            $info = $auth->revoke($auth->getRole($role), $id);
        }

        if (!$info) {
            Yii::$app->session->setFlash('error', Yii::t('app', 'There was some error while deleting user role.'));
            return $this->redirect(['index']);
        }

        Yii::$app->session->setFlash('success', Yii::t('app', 'You have successfuly deleted user and his role.'));
        
        return $this->redirect(['index']);
    }

  
    protected function findModel($id)
    {
        $model = User::findOne($id);

        if (is_null($model)) {
            throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
        } 

        return $model;
    }
}

views/user/_form.php
<?php
use app\rbac\models\AuthItem;
use kartik\password\PasswordInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Userof;

/* @var $this yii\web\View */
/* @var $user app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
        
		<?= $form->field($user, 'first_name')->textInput(
                ['placeholder' => Yii::t('app', 'First Name'), 'autofocus' => true])->label(false) ?>
				
		<?= $form->field($user, 'last_name')->textInput(
                ['placeholder' => Yii::t('app', 'Last Name'), 'autofocus' => true])->label(false) ?>
								
		<?= $form->field($user, 'designation')->textInput(
                ['placeholder' => Yii::t('app', 'Designation'), 'autofocus' => true])->label(false) ?>	
								
		<?= $form->field($user, 'address')->textInput(
                ['placeholder' => Yii::t('app', 'Address'), 'autofocus' => true])->label(false) ?>		
		
		<?= $form->field($user, 'username')->textInput(
                ['placeholder' => Yii::t('app', 'Create username'), 'autofocus' => true])->label(false) ?>
        
        <?= $form->field($user, 'email')->input('email', ['placeholder' => Yii::t('app', 'Enter e-mail')])->label(false) ?>
		
		<?= $form->field($user, 'mobile_no')->input('mobile_no', ['placeholder' => Yii::t('app', 'মোবাইল নাম্বার')])->label(false) ?>		

        <?php if ($user->scenario === 'create'): ?>

            <?= $form->field($user, 'password')->widget(PasswordInput::classname(), 
                ['options' => ['placeholder' => Yii::t('app', 'Password')]]) ?>

        <?php else: ?>

            <?= $form->field($user, 'password')->widget(PasswordInput::classname(),
                     ['options' => ['placeholder' => Yii::t('app', 'Password')]]) ?> 

        <?php endif ?>

    <div class="row">
    <div class="col-md-6">
        
		<?= $form->field($user, 'status')->dropDownList($user->statusList, ['prompt' => 'পদমর্যাদা অনুসারে'])->label(false) ?>
        <?php foreach (AuthItem::getRoles() as $item_name): ?>			
            <?php $roles[$item_name->name] = $item_name->name ?>			
        <?php endforeach ?>
		<?php $userId = \Yii::$app->user->identity->id; ?>
		<?php if( $userId== 2 && ($key = array_search('admin', $roles)) !== false) {
				unset($roles[$key]); ?>				
		<?php } ?>
		
		<?= $form->field($user, 'item_name')->dropDownList($roles, ['prompt' => 'পদমর্যাদা'])->label(false) ?>
		
        <?= $form->field($user, 'userof')->dropDownList(
			ArrayHelper::map(Userof::find()->all(), 'userof_id', 'title'),
			['prompt' => 'ব্যবহারকারী']
		) ?>
		
		<?= $form->field($user, 'photo')->fileInput(); ?>

    </div>
    </div>

    <div class="form-group">     
        <?= Html::submitButton($user->isNewRecord ? Yii::t('app', 'Create') 
            : Yii::t('app', 'Update'), ['class' => $user->isNewRecord 
            ? 'btn btn-success' : 'btn btn-primary']) ?>

        <?= Html::a(Yii::t('app', 'Cancel'), ['user/index'], ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>
 
</div>

views/user/create.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $user app\models\User */

$this->title = Yii::t('app', 'Create User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
?>
<div class="user-create">   

    <div class="col-md-5 well bs-component">

        <?= $this->render('_form', ['user' => $user]) ?>

    </div>

</div>

views/user/index.php
<?php
use app\helpers\CssHelper;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">
	<h1>       
        <span class="pull-right" style="padding-bottom:10px;">
			<?php if (Yii::$app->user->can('admin')){ ?>
				<?= Html::a(Yii::t('app', 'Create User'), ['create'], ['class' => 'btn btn-success']) ?>
			<?php } ?>            
        </span>         
    </h1>
	

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'summary' => false,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn',
				 'header' => 'ক্রমিক নং',
			],
            'username',
            'email:email',            
            [
                'attribute'=>'status',
                'filter' => $searchModel->statusList,
                'value' => function ($data) {
                    return $data->getStatusName($data->status);
                },
                'contentOptions'=>function($model, $key, $index, $column) {
                    return ['class'=>CssHelper::userStatusCss($model->status)];
                }
            ],            
            [
				'header' => 'ভূমিকা',
                'attribute'=>'item_name',
                'filter' => $searchModel->rolesList,
                'value' => function ($data) {
                    return $data->roleName;
                },
                'contentOptions'=>function($model, $key, $index, $column) {
                    return ['class'=>CssHelper::roleCss($model->roleName)];
                }
            ],
			[
				'header' => 'প্রোফাইল ছবি',
				'format' => 'html',
				'value'=>function($data) { return $data->photourl; },
			],	
			['class' => 'yii\grid\ActionColumn',
            'header' => "মেনু",
            'template' => '{view} {update} {delete}',
                'buttons' => [
                    'view' => function ($url, $model, $key) {
                        return Html::a('', $url, ['title'=>'View user', 'class'=>'glyphicon glyphicon-eye-open']);
                    },
                    'update' => function ($url, $model, $key) {
                        return Html::a('', $url, ['title'=>'Manage user', 'class'=>'glyphicon glyphicon-user']);
                    },
                    'delete' => function ($url, $model, $key) {
                        return Html::a('', $url, 
                        ['title'=>'Delete user', 
                            'class'=>'glyphicon glyphicon-trash',
                            'data' => [
                                'confirm' => Yii::t('app', 'Are you sure you want to delete this user?'),
                                'method' => 'post']
                        ]);
                    }
                ]

            ], 

        ], 

    ]); ?>

</div>

views/user/update.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $user app\models\User */

$this->title = Yii::t('app', 'Update User') . ': ' . $user->username;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $user->username, 'url' => ['view', 'id' => $user->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="user-update">
    	
    <div class="col-md-5 well bs-component">
		
        <?= $this->render('_form', ['user' => $user]) ?>

    </div>
	

</div>

views/user/view.php
<?php
use app\helpers\CssHelper;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1>
        <div class="pull-right" style="padding-bottom:10px;">
            <?= Html::a(Yii::t('app', 'Back'), ['index'], ['class' => 'btn btn-warning']) ?>
            <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], ['class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this user?'),
                    'method' => 'post',
                ],
            ]) ?>
        </div>
    </h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            'email:email',            
            [
                'attribute'=>'status',
                'value' => '<span class="'.CssHelper::userStatusCss($model->status).'">
                                '.$model->getStatusName($model->status).'
                            </span>',
                'format' => 'raw'
            ],
            [
                'attribute'=>'item_name',
                'value' => '<span class="'.CssHelper::roleCss($model->getRoleName()).'">
                                '.$model->getRoleName().'
                            </span>',
                'format' => 'raw'
            ],        
            'created_at:date',
            'updated_at:date',
        ],
    ]) ?>

</div>